name: Sync to GitLab

on:
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  sync-gitlab-saas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Sync to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_SAAS_TOKEN }}
          GITLAB_REPO: ${{ secrets.GITLAB_SAAS_REPO }}
        run: |
          git remote remove gitlab 2>/dev/null || true
          git remote add gitlab "${GITLAB_REPO}"
          git push --force --all "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO#https://}"
          git push --force --tags "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO#https://}"

  sync-gitlab-self-managed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Sync to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_SELF_MANAGED_TOKEN }}
          GITLAB_REPO: ${{ secrets.GITLAB_SELF_MANAGED_REPO }}
        run: |
          git remote remove gitlab 2>/dev/null || true
          git remote add gitlab "${GITLAB_REPO}"
          git push --force --all "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO#https://}"
          git push --force --tags "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO#https://}"
